stages:
  ingest:
    cmd: python industrial_maintenance/dataset.py
    deps:
      - industrial_maintenance/dataset.py
      - data/raw/industrial_equipment_anomaly_data.csv
    outs:
      - data/interim/cleaned_data.csv
      
  featurize:
    cmd: python industrial_maintenance/features.py
    deps:
      - industrial_maintenance/features.py
      - data/interim/cleaned_data.csv
    outs:
      - data/processed/featured_data.csv
      - models/preprocessor.joblib
  
  train:
    cmd: python industrial_maintenance/modeling/train.py
    deps:
      - industrial_maintenance/modeling/train.py
      - data/processed/featured_data.csv
    params:
      - model_type
      - train
      - random_forest
      - xgboost
    outs:
      - models/model.joblib