# Selection: "random_forest" or "xgboost"
model_type: "xgboost"

# Shared parameters
train:
  cv_folds: 5
  random_state: 42

# Random Forest Specifics
random_forest:
  param_grid:
    n_estimators: [100, 200]
    max_depth: [5, 10, null]
    min_samples_split: [2, 5]

# XGBoost Specifics
xgboost:
  param_grid:
    n_estimators: [100, 200]
    max_depth: [3, 6, 9]
    learning_rate: [0.01, 0.1]
    subsample: [0.8, 1.0]